name: Release

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

env:
  PYPI_TOKEN: "${{ secrets.PYPI_TOKEN }}"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python project
        uses: ./.github/actions/setup-python
        with:
          tool-versions-path: .tool-versions

      - name: Run lint
        run: make lint

      - name: Run test
        run: make test

      - name: Run publish
        run: make release
